### PR TITLE
Bundle the alert sound instead of loading a Youtube iframe

### PR DESCRIPTION
**Pull request by mquandalle**
Advantages:
- doesn’t load a full Youtube page just to play a sound
- load once, and play multiple time from that
- work in offline mode

The sound used is released in the public domain. I found it on https://www.freesound.org which has a filter to restrict to public domain only sounds, so feel free to find a better one :-)

### CODE REVIEW

**Comment by stubailo** [comment]
If it's public domain, do I have to do anything about licensing?

And thank you very much!

**Comment by stubailo** [comment]
Oh nvm I see you added something. Going to publish a new version in a bit!

**Comment by mquandalle** [comment]
I also forgot to remove the fixed point 2. in the “Future improvements to make” section of the Readme.

(actually I didn’t see it at first, I started to read the code and saw the youtube iframe there ;-)) Readme? Not for me.

**Comment by stubailo** [comment]
Fixed! and published 1.1.0. Thanks again!

**Comment by mquandalle** [comment]
Isn’t Meteor 1.3 suppose to fix `1.`?

**Comment by stubailo** [comment]
not last I heard. It might actually be kind of hard to figure out how many restarts are necessary for different cases. But I think it will be done post 1.3.

**Pull request merged**
